[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "code_runner"
version = "0.1.0"
description = "A simple code runner application"
authors = [{name = "Arnab Banik", email = "arnabbanik9@gmail.com"}]